
GET http://localhost:8080/query?id=1

> {%
client.test("Test query get endpoint", function (){
    client.log("Test query get endpoint");
    client.log(response.body)
    client.assert(response.status === 200, "response status is 200");
});
%}